### PR TITLE
Test case parse error

### PR DESCRIPTION
**Pull request by scottconnerly**

### CODE REVIEW

**Comment by freekmurze** [comment]
Can you rebase this?

**Comment by scottconnerly** [comment]
Rebased.

Note to self for later, here's the proper way to rebase commits that are already pushed to Github: https://blog.liplex.de/how-to-squash-already-pushed-commits/

**Comment by scottconnerly** [comment]
This is finally ready to be merged again. Sorry for the delay.

**Comment by scottconnerly** [comment]
Is there more you would like to see from this Pull Request before it is merged?

**Comment by freekmurze** [comment]
Code looks good, when I have the time, I'll review in detail. High chance that it'll get pulled.

There are some merge conflicts though, could you rebase this?

**Comment by scottconnerly** [comment]
upstream/master merged in. I don't believe I'm able to squash that commit away. But it's ready to merge.

**Comment by freekmurze** [comment]
Thank you! Pulling this in now, will review and tag a new version somewhere next week.

**Pull request merged**
