### PR TITLE
**[FEATURE]** Allows to configure a custom view for the e-mail notification

### PR DESCRIPTION
**Pull request by emielmolenaar**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I have not added tests to prove that the code in this PR works. E-mail tests are already there.

---

### Description

This patch allows one to configure a custom view for the e-mail notification.

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, thank you for this contribution.

This PR is breaking for people who upgrade from a previous version (and that do not have the config value). Could you please ensure that this PR is backwards compatible?

**Comment by emielmolenaar** [comment]
Isn't backward compatibility covered by https://github.com/spatie/laravel-failed-job-monitor/blob/master/src/FailedJobMonitorServiceProvider.php#L28 ? If one does not have the "view" key and value available in their configuration, the configuration of the package is used and so falls back to the default view.

Please correct me if I'm wrong :smiley:

**Comment by freekmurze** [comment]
You're right! 😄

**Comment by freekmurze** [comment]
Thank you!

**Comment by emielmolenaar** [comment]
All right, thanks for the merge and this nice package :+1:

**Pull request merged**
